version: '3'
services:
  nginx:
    build:
      # Dockerfile の保存場所を指定する
      context   : ./nginx/
      # Dockerfile 名を指定する
      dockerfile: Dockerfile-nginx
    # イメージ名
    image         : practice-nginx
    # コンテナ名
    container_name: practice-nginx
    # ポートフォワード
    ports:
      - 80:80
  # ビルド済のコンテナを公開する場合 : ファイルの変更は検知できない
  app-1:
    build:
      context   : ./app-1/
      dockerfile: Dockerfile-app-1
    image         : practice-app-1
    container_name: practice-app-1
  # ボリュームマウントすることで静的ファイルの変更を反映できるようにする
  app-2:
    build:
      context   : ./app-2/
      dockerfile: Dockerfile-app-2
    image         : practice-app-2
    container_name: practice-app-2
    # ボリュームマウントして実行する
    volumes:
      - ./app-2/src:/src
    working_dir: /src/
    # node コマンドのパスを認識させるため sh -c が必要
    command: [sh, -c, node /src/index.js]
    # 直接公開する場合は以下を書く
    #ports:
    #  - 3002:3002
